// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZuwAqpMr7dIgsb80BEkSdJsDIUDCgeqs',
    appId: '1:699164222259:web:8a4036f5e7cadab96d1446',
    messagingSenderId: '699164222259',
    projectId: 'expsend-mobile-app',
    authDomain: 'expsend-mobile-app.firebaseapp.com',
    storageBucket: 'expsend-mobile-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATlkL82FthXA3qZzfjd1zTYS2Hs1gBalU',
    appId: '1:699164222259:android:80f99d1eab10ea806d1446',
    messagingSenderId: '699164222259',
    projectId: 'expsend-mobile-app',
    storageBucket: 'expsend-mobile-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBus2AAMY3mXqlH63woLRzLhzEEgzmmdl8',
    appId: '1:699164222259:ios:b6aefe07fca7ca1c6d1446',
    messagingSenderId: '699164222259',
    projectId: 'expsend-mobile-app',
    storageBucket: 'expsend-mobile-app.appspot.com',
    iosBundleId: 'com.example.exspendMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBus2AAMY3mXqlH63woLRzLhzEEgzmmdl8',
    appId: '1:699164222259:ios:6e9f63ae0cd6064c6d1446',
    messagingSenderId: '699164222259',
    projectId: 'expsend-mobile-app',
    storageBucket: 'expsend-mobile-app.appspot.com',
    iosBundleId: 'com.example.exspendMobileApp.RunnerTests',
  );
}
